services:
  clientes: &clientes http://localhost:3001
  contas: &contas http://localhost:3002
  transacoes: &transacoes http://localhost:3003

routes:
  clientes:
    - path: /meus-dados
      method: GET
      roles: ["TITULAR", "OPERADOR", "ADMIN"]
    - path: /clientes/*
      method: ALL
      roles: ["ADMIN"]

  contas:
    - path: /minhas-contas
      method: GET
      roles: ["TITULAR", "OPERADOR", "ADMIN"]
    - path: /contas/*
      method: ALL
      roles: ["ADMIN"]

  transacoes:
    - path: /minhas-transacoes
      method: ALL
      roles: ["TITULAR", "OPERADOR", "ADMIN"]
    - path: /transacoes/*
      method: ALL
      roles: ["OPERADOR", "ADMIN"]
